### PR TITLE
Improve code stability of `Analyzer`

### LINKED ISSUE #28: [Suggestion] How about creating an Enum Type for the language field in the Analyzer?
Hello! I'm leaving a suggestion to manage the Language field in the Analyzer as Enum. 

If we manage the language fields in the analyzer with Enum, we can manage the match statements with `Language::Rust`, `Language::Python`, and `Language::Other(other_lang)`. which will enable more stable matches.

### now
https://github.com/balpan-rs/balpan/blob/ec3c71cc8da833b571994bc76fe85f7b079c080e/src/analyzer.rs#L9-L13

### suggestion

```rust
 pub struct Analyzer { 
     pub source_code: String, 
     pub language: Language,
 } 
``` 
 
 
### Language Enum's blueprint

```rust
/// language enums
enum Language {
    Rust,
    Python,
    Other(String),
}

impl Language {
    fn as_str(&self) -> &str {
        match self {
            Language::Rust => "rust",
            Language::Python => "python",
            Language::Other(other) => other.as_str(),
        }
    }

    fn from_string(&self, lang: String) -> Self {
        match lang.as_str() {
            "rust" => Language::Rust,
            "python" => Language::Python,
            _ => Language::Other(String::from(lang)),
        }
    }
}
```

### Benefit
By doing this, it enables more dependable pattern matching as illustrated below. Moreover, it seems that there would be no need to modify the existing conversion code that uses as_str().

```rust 
fn top_level_node_type(&self) -> &str {
        match self.language {
            Language::Rust => "source_file",
            Language::Python => "module",
            Language::Other(_) => "",
        }
    }
```

### PR DESCRIPTION
**Pull request by nerdchanii**
Thank you for your positive response to the issue I submitted.

## linked issue

It resolve #28.

## works

- Change the `language` field of the Analyzer to a Language Enum.
- Replace to test code due to modifications in the constructor API caused by the type change of the `language` filed in the `Analyzer`.

### additional description

I've been considering where to place the Language Enum, but I haven't found the most suitable location yet. Do you think the current placement is okay? 

---
P.S. 
As I couldn't accurately determine the commit convention of this project, I followed a similar approach as much as possible. I hope this work proves to be helpful.:)

### CODE REVIEW

**Comment by malkoG** [comment]
I recommend move definition of `Language` to another file for future purpose. (ex. `language.rs`)

I am implementing `Scanner` struct right now, and this has a role that scans all of files, and parses and replace source code.

Before parsing source code, It takes extension from filename and extension will be mapped to `Language` enum. Then `Analyzer` comes

**Comment by nerdchanii** [comment]
Oh, that sounds good. I've separated the `Language` Enum into the "language.rs" module, as instructed.

If I understand correctly, `Language` could potentially become a single massive module in the future. Am I understanding this correctly?

**Comment by malkoG** [comment]
Yes. That's right. Balpan will support all languages that supported by tree-sitter

But, Some special cases will not be supported 😁😁 (e.g. `gitcommit`, `embeded_template`, `markdown`, `html`, ...)

**Comment by nerdchanii** [comment]
Oh, I see! That sounds so great. The plan is awesome!👍

**Comment by malkoG** [comment]
Thanks for your work, again! 

https://github.com/balpan-rs/balpan/commit/47b85e45cfd6d72c8310f1cc9776722d11e3a1e1

**Pull request closed without merging**
